configuration:
  endpoint: http://151.1.165.20:8085/configurations/entries
  baseUrl: marccat

logging:
  level:
    root: ERROR
    net.sf: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    ru.yandex: ERROR
    org.folio.marccat: INFO

server:
  port: 8080

